app = "fly-io-redis"
primary_region = "ams"

[[vm]]
  size = "shared-cpu-1x"

[metrics]
  port = 9091
  path = "/metrics"

[build]
  dockerfile = "Dockerfile"

# Uncomment these lines for public internet access to Redis on port 10000
#
# [[services]]
# internal_port = 6379
# protocol      = "tcp"

#   [[services.ports]]
#   port     = "10000"

#   [[services.tcp_checks]]
#   interval = 10000
#   timeout  = 2000
